name: PoloCloud-Entities
author: iPommes
version: 1.0
main: de.polocloud.plugin.entity.bootstrap.CloudEntityBootstrap
api-version: 1.18

commands:
  cloudentity:
    aliases:
      - entity
      - entities
      - cloudentites